# Generated by Django 6.0.3 on 2026-03-17 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('ready_for_test', 'Ready for test'), ('closed', 'Closed'), ('needs_info', 'Needs info'), ('rejected', 'Rejected'), ('postponed', 'Postponed')], default='new', max_length=20)),
                ('type', models.CharField(choices=[('bug', 'Bug'), ('question', 'Question'), ('enhancement', 'Enhancement')], default='bug', max_length=20)),
                ('severity', models.CharField(choices=[('wishlist', 'Wishlist'), ('minor', 'Minor'), ('normal', 'Normal'), ('important', 'Important'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
