# Generated by Django 6.0.3 on 2026-03-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_attachment_comment'),
        ('issues', '0002_issue_deadline'),
    ]

    operations = []
