# Generated by Django 6.0.3 on 2026-04-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0007_issueactivity"),
    ]

    operations = [
        migrations.CreateModel(
            name="DueDatePreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("days_from_today", models.PositiveSmallIntegerField()),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "days_from_today"],
            },
        ),
        migrations.CreateModel(
            name="IssuePriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("color", models.CharField(default="#22c55e", max_length=7)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="IssueSeverity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("color", models.CharField(default="#6b7280", max_length=7)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="IssueTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("color", models.CharField(default="#70728f", max_length=7)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IssueType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("color", models.CharField(default="#4c9aff", max_length=7)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="issue",
            name="issue_type",
            field=models.CharField(default="bug", max_length=20),
        ),
        migrations.AlterField(
            model_name="issue",
            name="priority",
            field=models.CharField(default="normal", max_length=10),
        ),
        migrations.AlterField(
            model_name="issue",
            name="severity",
            field=models.CharField(default="normal", max_length=20),
        ),
        migrations.AddField(
            model_name="issue",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="issues", to="issues.issuetag"
            ),
        ),
    ]
