# Generated by Django 6.0.3 on 2026-04-16 13:35

from django.db import migrations


def seed_catalog_defaults(apps, schema_editor):
    IssueType = apps.get_model("issues", "IssueType")
    IssueSeverity = apps.get_model("issues", "IssueSeverity")
    IssuePriority = apps.get_model("issues", "IssuePriority")
    DueDatePreset = apps.get_model("issues", "DueDatePreset")

    type_defaults = [
        {"name": "Bug", "slug": "bug", "color": "#e44057", "order": 0},
        {"name": "Question", "slug": "question", "color": "#8b5cf6", "order": 1},
        {"name": "Enhancement", "slug": "enhancement", "color": "#0891b2", "order": 2},
    ]
    for item in type_defaults:
        IssueType.objects.get_or_create(slug=item["slug"], defaults=item)

    severity_defaults = [
        {"name": "Wishlist", "slug": "wishlist", "color": "#6b7280", "order": 0},
        {"name": "Minor", "slug": "minor", "color": "#ca8a04", "order": 1},
        {"name": "Normal", "slug": "normal", "color": "#16a34a", "order": 2},
        {"name": "Important", "slug": "important", "color": "#ea580c", "order": 3},
        {"name": "Critical", "slug": "critical", "color": "#b91c1c", "order": 4},
    ]
    for item in severity_defaults:
        IssueSeverity.objects.get_or_create(slug=item["slug"], defaults=item)

    priority_defaults = [
        {"name": "Low", "slug": "low", "color": "#eab308", "order": 0},
        {"name": "Normal", "slug": "normal", "color": "#22c55e", "order": 1},
        {"name": "High", "slug": "high", "color": "#ef4444", "order": 2},
    ]
    for item in priority_defaults:
        IssuePriority.objects.get_or_create(slug=item["slug"], defaults=item)

    preset_defaults = [
        {"name": "In one week", "days_from_today": 7, "order": 0},
        {"name": "In two weeks", "days_from_today": 14, "order": 1},
        {"name": "In one month", "days_from_today": 30, "order": 2},
        {"name": "In three months", "days_from_today": 90, "order": 3},
    ]
    for item in preset_defaults:
        DueDatePreset.objects.get_or_create(name=item["name"], defaults=item)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0008_duedatepreset_issuepriority_issueseverity_issuetag_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_catalog_defaults, reverse_code=noop_reverse),
    ]
