# Generated by Django 6.0.3 on 2026-04-16

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    Issue = apps.get_model('issues', 'Issue')
    IssueType = apps.get_model('issues', 'IssueType')
    IssuePriority = apps.get_model('issues', 'IssuePriority')
    IssueSeverity = apps.get_model('issues', 'IssueSeverity')

    for issue in Issue.objects.all():
        # issue_type
        if issue.issue_type:
            obj = IssueType.objects.filter(slug=issue.issue_type).first()
            if obj:
                issue.issue_type_new = obj

        # priority
        if issue.priority:
            obj = IssuePriority.objects.filter(slug=issue.priority).first()
            if obj:
                issue.priority_new = obj

        # severity
        if issue.severity:
            obj = IssueSeverity.objects.filter(slug=issue.severity).first()
            if obj:
                issue.severity_new = obj

        issue.save()


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_seed_issue_catalog_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_type_new',
            field=models.ForeignKey(
                to='issues.issuetype',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
            ),
        ),
        migrations.AddField(
            model_name='issue',
            name='priority_new',
            field=models.ForeignKey(
                to='issues.issuepriority',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
            ),
        ),
        migrations.AddField(
            model_name='issue',
            name='severity_new',
            field=models.ForeignKey(
                to='issues.issueseverity',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
            ),
        ),
        migrations.RunPython(forwards),
        migrations.RemoveField(
            model_name='issue',
            name='issue_type',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='severity',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='issue_type_new',
            new_name='issue_type',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='priority_new',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='severity_new',
            new_name='severity',
        ),
    ]
