# Generated by Django 6.0.3 on 2026-03-17 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
